//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgeFactor
    {
        public tblAgeFactor()
        {
            this.tblTestParameters = new HashSet<tblTestParameter>();
        }
    
        public int ID { get; set; }
        public string AgeRange { get; set; }
    
        public virtual ICollection<tblTestParameter> tblTestParameters { get; set; }
    }
}
