//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        public tblBranch()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
        }
    
        public int ID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
    }
}
