//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChapter
    {
        public tblChapter()
        {
            this.tblTests = new HashSet<tblTest>();
        }
    
        public int ChapterID { get; set; }
        public string ChapterName { get; set; }
    
        public virtual ICollection<tblTest> tblTests { get; set; }
    }
}
