//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblPatientTests = new HashSet<tblPatientTest>();
            this.tblPatients = new HashSet<tblPatient>();
        }
    
        public string Email { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Designation { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BranchFID { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual ICollection<tblPatientTest> tblPatientTests { get; set; }
        public virtual ICollection<tblPatient> tblPatients { get; set; }
    }
}
