//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public tblPatient()
        {
            this.tblPatientTests = new HashSet<tblPatientTest>();
        }
    
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string EmailFID { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> TotalDiscountedCost { get; set; }
        public Nullable<decimal> RemainingPaidRupees { get; set; }
        public string monthlyNo { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual ICollection<tblPatientTest> tblPatientTests { get; set; }
    }
}
