//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int Id { get; set; }
        public int TestParameterId { get; set; }
        public string ValueResult { get; set; }
        public int PatientTestId { get; set; }
    }
}
