//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naveedLabDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTest
    {
        public int Id { get; set; }
        public string TestName { get; set; }
        public int ChapterFID { get; set; }
        public Nullable<int> Charges { get; set; }
    
        public virtual tblChapter tblChapter { get; set; }
    }
}
